/**
 * EODForecastCard — Tomorrow's prediction generated by AI at 3:20 PM daily.
 *
 * Shows:
 *   - Today's summary
 *   - Tomorrow gap prediction
 *   - Trap zones (bull/bear)
 *   - Reversal levels
 *   - Best strikes to watch
 *   - Time windows
 *   - AI confidence
 */

import React, { useState, useEffect } from "react";

const PURPLE = "#a855f7";
const GREEN = "#26a69a";
const RED = "#ef5350";
const BLUE = "#2962ff";
const ORANGE = "#FF9F0A";
const YELLOW = "#FFD60A";
const FG = "#d4d4d8";
const FG_DIM = "#71717a";
const BG = "#0a0a0a";
const CARD = "#0f0f10";
const BORDER = "#1f1f24";

async function getJSON(url) {
  try { const r = await fetch(url); return await r.json(); } catch { return null; }
}
async function postJSON(url, body = {}) {
  try {
    const r = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) });
    return await r.json();
  } catch { return null; }
}

function gapColor(gap) {
  if (!gap) return FG;
  if (gap.includes("UP")) return GREEN;
  if (gap.includes("DOWN")) return RED;
  return YELLOW;
}

function biasColor(bias) {
  if (!bias) return FG;
  if (bias === "BULLISH") return GREEN;
  if (bias === "BEARISH") return RED;
  return YELLOW;
}

export default function EODForecastCard() {
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [generating, setGenerating] = useState(false);

  const load = async () => {
    const r = await getJSON("/api/ai/eod-forecast");
    if (r && !r.error) setData(r);
    setLoading(false);
  };

  useEffect(() => {
    load();
    // Refresh every 5 min
    const iv = setInterval(() => {
      if (document.visibilityState === "visible") load();
    }, 300000);
    return () => clearInterval(iv);
  }, []);

  const generateNow = async () => {
    if (!window.confirm("Generate fresh AI forecast now? Uses Claude API.")) return;
    setGenerating(true);
    await postJSON("/api/ai/eod-forecast/generate");
    await load();
    setGenerating(false);
  };

  if (loading) {
    return (
      <div style={wrap}>
        <div style={{ color: FG_DIM, fontSize: 12 }}>Loading EOD forecast...</div>
      </div>
    );
  }

  if (!data || data.error) {
    return (
      <div style={wrap}>
        <div style={headerRow}>
          <div>
            <div style={{ fontSize: 11, color: PURPLE, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase" }}>
              🌅 AI EOD FORECAST
            </div>
            <div style={{ fontSize: 11, color: FG_DIM, marginTop: 2 }}>
              Generated daily at 3:20 PM IST
            </div>
          </div>
          <button onClick={generateNow} disabled={generating} style={btnPrimary}>
            {generating ? "Generating..." : "🤖 Generate Now"}
          </button>
        </div>
        <div style={{ color: FG_DIM, fontSize: 11, padding: 12, textAlign: "center" }}>
          {data?.error || "No forecast yet. Auto-generates daily at 3:20 PM."}
        </div>
      </div>
    );
  }

  // Parse JSON fields if string
  let trapZones = data.trap_zones;
  let reversalLevels = data.reversal_levels;
  let bestStrikes = data.best_strikes;
  let timeWindows = data.time_windows;

  if (typeof trapZones === "string") try { trapZones = JSON.parse(trapZones); } catch {}
  if (typeof reversalLevels === "string") try { reversalLevels = JSON.parse(reversalLevels); } catch {}
  if (typeof bestStrikes === "string") try { bestStrikes = JSON.parse(bestStrikes); } catch {}
  if (typeof timeWindows === "string") try { timeWindows = JSON.parse(timeWindows); } catch {}

  return (
    <div style={wrap}>
      {/* Header */}
      <div style={headerRow}>
        <div>
          <div style={{ fontSize: 11, color: PURPLE, fontWeight: 700, letterSpacing: 1, textTransform: "uppercase" }}>
            🌅 AI EOD FORECAST · {data.date}
          </div>
          <div style={{ fontSize: 11, color: FG_DIM, marginTop: 2 }}>
            Generated by Claude Haiku · {data.generated_at?.slice(11, 16)} IST
          </div>
        </div>
        <button onClick={generateNow} disabled={generating} style={btnGhost}>
          {generating ? "..." : "🔄 Regenerate"}
        </button>
      </div>

      {/* Today summary */}
      {data.today_summary && (
        <div style={{
          background: BG,
          border: `1px solid ${BORDER}`,
          borderRadius: 4,
          padding: 12,
          marginBottom: 12,
          fontSize: 12,
          color: FG,
          lineHeight: 1.5,
        }}>
          <div style={labelStyle}>📊 Today's Story</div>
          <div style={{ marginTop: 4 }}>{data.today_summary}</div>
        </div>
      )}

      {/* Tomorrow Gap + Bias */}
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginBottom: 12 }}>
        <div style={cellBox}>
          <div style={labelStyle}>TOMORROW GAP</div>
          <div style={{
            fontSize: 16, fontWeight: 700,
            color: gapColor(data.tomorrow_gap),
            marginTop: 4,
          }}>
            {data.tomorrow_gap || "—"}
          </div>
        </div>
        <div style={cellBox}>
          <div style={labelStyle}>TOMORROW BIAS</div>
          <div style={{
            fontSize: 16, fontWeight: 700,
            color: biasColor(data.tomorrow_bias),
            marginTop: 4,
          }}>
            {data.tomorrow_bias || "—"}
          </div>
        </div>
      </div>

      {/* Trap Zones */}
      {trapZones && (trapZones.bull_trap_above || trapZones.bear_trap_below) && (
        <div style={{ marginBottom: 12 }}>
          <div style={labelStyle}>🎯 TRAP ZONES</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 6 }}>
            {trapZones.bull_trap_above && (
              <div style={{ ...cellBox, borderColor: `${RED}33` }}>
                <div style={{ fontSize: 9, color: RED, fontWeight: 700 }}>▼ BULL TRAP</div>
                <div style={{ fontSize: 16, fontWeight: 700, color: RED, marginTop: 4 }}>
                  Above {trapZones.bull_trap_above}
                </div>
              </div>
            )}
            {trapZones.bear_trap_below && (
              <div style={{ ...cellBox, borderColor: `${GREEN}33` }}>
                <div style={{ fontSize: 9, color: GREEN, fontWeight: 700 }}>▲ BEAR TRAP</div>
                <div style={{ fontSize: 16, fontWeight: 700, color: GREEN, marginTop: 4 }}>
                  Below {trapZones.bear_trap_below}
                </div>
              </div>
            )}
          </div>
          {trapZones.logic && (
            <div style={{ fontSize: 11, color: FG_DIM, marginTop: 6, fontStyle: "italic" }}>
              {trapZones.logic}
            </div>
          )}
        </div>
      )}

      {/* Reversal Levels */}
      {reversalLevels && (reversalLevels.strong_support || reversalLevels.strong_resistance) && (
        <div style={{ marginBottom: 12 }}>
          <div style={labelStyle}>🔄 REVERSAL LEVELS</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 6 }}>
            {reversalLevels.strong_support && (
              <div style={cellBox}>
                <div style={{ fontSize: 9, color: GREEN, fontWeight: 700 }}>STRONG SUPPORT</div>
                <div style={{ fontSize: 14, fontWeight: 700, color: GREEN, marginTop: 4 }}>
                  {reversalLevels.strong_support}
                </div>
              </div>
            )}
            {reversalLevels.strong_resistance && (
              <div style={cellBox}>
                <div style={{ fontSize: 9, color: RED, fontWeight: 700 }}>STRONG RESISTANCE</div>
                <div style={{ fontSize: 14, fontWeight: 700, color: RED, marginTop: 4 }}>
                  {reversalLevels.strong_resistance}
                </div>
              </div>
            )}
          </div>
        </div>
      )}

      {/* Best Strikes */}
      {bestStrikes && Array.isArray(bestStrikes) && bestStrikes.length > 0 && (
        <div style={{ marginBottom: 12 }}>
          <div style={labelStyle}>🎯 BEST STRIKES TO WATCH</div>
          {bestStrikes.map((s, i) => (
            <div key={i} style={{
              background: BG,
              border: `1px solid ${s.type === "CE" ? GREEN : RED}33`,
              borderRadius: 4,
              padding: "6px 10px",
              marginTop: 6,
              fontSize: 11,
              color: FG,
            }}>
              <span style={{ color: s.type === "CE" ? GREEN : RED, fontWeight: 700 }}>
                {s.type} {s.strike}
              </span>
              <span style={{ color: FG_DIM, marginLeft: 8 }}>
                {s.reason}
              </span>
            </div>
          ))}
        </div>
      )}

      {/* Time Windows */}
      {timeWindows && (timeWindows.best || timeWindows.avoid) && (
        <div style={{ marginBottom: 12 }}>
          <div style={labelStyle}>⏰ TIME WINDOWS</div>
          <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 6 }}>
            <div>
              <div style={{ fontSize: 9, color: GREEN, fontWeight: 700, marginBottom: 4 }}>✓ BEST</div>
              {(timeWindows.best || []).map((w, i) => (
                <div key={i} style={{ fontSize: 11, color: FG, padding: "2px 0" }}>{w}</div>
              ))}
            </div>
            <div>
              <div style={{ fontSize: 9, color: RED, fontWeight: 700, marginBottom: 4 }}>✗ AVOID</div>
              {(timeWindows.avoid || []).map((w, i) => (
                <div key={i} style={{ fontSize: 11, color: FG, padding: "2px 0" }}>{w}</div>
              ))}
            </div>
          </div>
        </div>
      )}

      {/* Confidence */}
      {data.confidence !== undefined && data.confidence !== null && (
        <div style={{
          padding: "8px 12px",
          background: BG,
          border: `1px solid ${BORDER}`,
          borderRadius: 4,
          display: "flex",
          justifyContent: "space-between",
          alignItems: "center",
        }}>
          <span style={{ fontSize: 11, color: FG_DIM }}>AI Confidence</span>
          <span style={{
            fontSize: 14, fontWeight: 700,
            color: data.confidence >= 70 ? GREEN : data.confidence >= 50 ? YELLOW : RED,
          }}>
            {data.confidence}%
          </span>
        </div>
      )}
    </div>
  );
}

const wrap = {
  background: CARD,
  border: `1px solid ${BORDER}`,
  borderRadius: 6,
  padding: 16,
  marginBottom: 12,
  fontFamily: "-apple-system, 'Segoe UI', system-ui, sans-serif",
};

const headerRow = {
  display: "flex",
  justifyContent: "space-between",
  alignItems: "center",
  paddingBottom: 10,
  borderBottom: `1px solid ${BORDER}`,
  marginBottom: 12,
};

const labelStyle = {
  fontSize: 9,
  color: FG_DIM,
  fontWeight: 600,
  letterSpacing: 0.5,
  textTransform: "uppercase",
};

const cellBox = {
  background: BG,
  border: `1px solid ${BORDER}`,
  borderRadius: 4,
  padding: "10px 12px",
};

const btnPrimary = {
  background: PURPLE,
  color: "#fff",
  border: "none",
  padding: "6px 14px",
  borderRadius: 4,
  fontSize: 11,
  fontWeight: 700,
  cursor: "pointer",
};

const btnGhost = {
  background: "transparent",
  color: FG_DIM,
  border: `1px solid ${BORDER}`,
  padding: "5px 10px",
  borderRadius: 3,
  fontSize: 10,
  fontWeight: 500,
  cursor: "pointer",
};
